version: 2.1
jobs:
  build:
    docker:
      - image:  'node:12.13.1'
    steps:
      - checkout
      - run: 
        name: Run npm install 
        command: npm install
      - run:
        name: Build the application
        command: npm run build